### ISSUE TITLE
CollectionResponse fails to deserialize if NotFound contains any Identifiers due to Identifier being an abstract class

### ISSUE THREAD

**Issue by mfiferna** [bytewisemarissa/HelpfulThings.Connect.Scryfall#1]
Hi, 
first of all, thank you for making this library, and for making it publicly accessible. 

I've run into an issue with the CollectionAsync call. 
When deserializing the CollectionResponse, the NotFound list cannot be deserialized due to Identifier being an abstract class.

I think the whole Identifiers architecture needs a bit of rework, as it doesn't (without implementing Identifier with my own class) allow full usage of the API. This library allows a single Identifier to be Name / MtgoIdentifier / ScryfallIdentifier /etc, while the API allows for a single identifier to be all of these at the same time. 

Quote: 

> Each submitted card identifier must be a JSON object with one **or more** of the keys id, mtgo_id, multiverse_id, oracle_id, illustration_id, name, set, and collector_number. 

If you don't wish to deal with this for any reason, I'd be willing to do it and make a pull request, I'd just need a bit of guidance on how you would like it to be architected. 

Edit: _Honestly, as the simplest solution, Identifier could be turned into a poco with all the props, ditching the abstract stuff altogether_

Thanks.

**Comment by bytewisemarissa** [comment]
Thanks for using this library it's a great feeling to have a user.

So looking back at the documentation going to pull that whole section for reference

> ## Card Identifiers
>
> Each submitted card identifier must be a JSON object with one or more of the keys `id`, `mtgo_id`, `multiverse_id`, `oracle_id`, `illustration_id`, `name`, `set`, and `collector_number`. **The following combinations are valid identifier schemas**:
>
> | Schema                 | Format  | Description                                                  |
> | ---------------------- | ------- | ------------------------------------------------------------ |
> | `id`                   | UUID    | Finds a card with the specified Scryfall `id`.               |
> | `mtgo_id`              | Integer | Finds a card with the specified `mtgo_id` or `mtgo_foil_id`. |
> | `multiverse_id`        | Integer | Finds a card with the specified value among its `multiverse_ids`. |
> | `oracle_id`            | UUID    | Finds the newest edition of cards with the specified `oracle_id`. |
> | `illustration_id`      | UUID    | Finds the preferred scans of cards with the specified `illustration_id`. |
> | `name`                 | String  | Finds the newest edition of a card with the specified `name`. |
> | `name,set`             | Strings | Finds a card matching the specified `name` and `set`.        |
> | `collector_number,set` | Strings | Finds a card with the specified `collector_number` and `set`. Note that collector numbers are *strings*. |
>
> Multiple identifier schemas may be included in a single request. Each identifier will return up to one card. Identifiers that are not found will be returned in the `not_found` array. While cards will be returned in the order that they were requested, cards that aren’t found will throw off the mapping of request identifiers to results, so you should not rely on positional index alone while parsing the data.

I think the important part to note here is that it goes on to list the valid combinations. In doing some testing in postman it looks like whatever identifier is satisfied first gets used, my hunch is its the order of the list.

So take the following request / response

```json
{
  "identifiers": [
    {
        "id": "0001b119-a224-4d24-879c-aeb2cc9861af"
    },
    {
        "name": "Black Lotus"
    }
  ]
}
```

```json
{
    "object": "list",
    "not_found": [],
    "data": [
        {
            "id": "0001b119-a224-4d24-879c-aeb2cc9861af"
            "name": "Holistic Wisdom",
            <CLIPPED FOR BREVITY>
        },
        {
            "id": "bd8fa327-dd41-4737-8f19-2cf5eb1f7cdd",        
            "name": "Black Lotus",
            <CLIPPED FOR BREVITY>
        }
    ]
}
```

Which works as expected vs. the following request response

```json
{
  "identifiers": [
    {
        "id": "0001b119-a224-4d24-879c-aeb2cc9861af",
        "name": "Black Lotus"
    }
  ]
}
```

```json
{
    "object": "list",
    "not_found": [],
    "data": [
        {
            "id": "0001b119-a224-4d24-879c-aeb2cc9861af",
            "name": "Holistic Wisdom",
            <CLIPPED FOR BREVITY>
        }
    ]
}
```

I tried flipping the order it doesn't seem to matter. So I do disagree about the abstraction not being needed. I chose to use opposing identifiers to try and figure out the identifier parsing strategy.

That said I have created a test that throws the same exception and I should be able to fix it by implementing a custom deserializer. I'm actively using this for a closed source project so I'm actively in this code right now so I'll probably get to it this weekend. Just as a heads up I'm on Debian and .NET 7 is no longer support so the library will target .NET 8 when the update hits.

**Comment by bytewisemarissa** [comment]
Should be fixed now, give it a shot. If you have any problems lemme know and I can take another look.
